# Use makefile to create pdf and then run clean.sh to delete aux

PAPER=Lab02-Barber-Nail.tex  # set the path to your TeX file here
CLEAN=clean.sh

PAPER:  ## Compile paper
	pdflatex Lab02-Barber-Nail.tex

CLEAN:  ## Clean output files
	sh clean.sh

