# Use makefile to create pdf and then run clean.sh to delete output files

PAPER=Final_Lab-Barber_Nail.tex  # set the path to your TeX file here

CLEAN: PAPER  				# Clean output files
	sh clean.sh
PAPER:					# Compile pdf
	pdflatex Final_Lab_Barber_Nail.tex
