# Use makefile to create pdf and then run clean.sh to delete output files

PAPER=Lab04-Barber-Nail.tex  # set the path to your TeX file here

CLEAN: PAPER  				# Clean output files
	sh clean.sh
PAPER:  					# Compile pdf
	pdflatex Lab05-Barber-Nail.tex
